/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.PasajeData;
import AccesoADatos.PasajeroData;
import Entidades.Pasaje;
import Entidades.Pasajero;
import Entidades.Ruta;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author emanu
 */
public class RegistroDePasajesView extends javax.swing.JInternalFrame {
      private PasajeroData pasData;
      private PasajeData pasaData = new PasajeData();
      private Pasaje pasajeActual = null;
      private DefaultTableModel modelo;
      private List<Pasaje> pasajes;
      
    public RegistroDePasajesView() {
        initComponents();
        
        modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                    return false;   
            }
        };
        
        
        pasData = new PasajeroData();
        
        armarCabeceraTabla();
        jBEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTdnipasajero = new javax.swing.JTextField();
        jBsalir = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jbBuscarDni = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPasajes = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PASAJES VENDIDOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.gray));

        jLabel3.setText("DNI Pasajero:");

        jBsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8-salida-de-emergencia-48.png"))); // NOI18N
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8-eliminar-papelera-48.png"))); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jbBuscarDni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8-busca-mas-20.png"))); // NOI18N
        jbBuscarDni.setText("Buscar");
        jbBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarDniActionPerformed(evt);
            }
        });

        jtPasajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPasajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jTdnipasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTdnipasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarDni))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed

        int filaSelecionada = jtPasajes.getSelectedRow();
        if (filaSelecionada!=-1) {
       
            
            Object idPasajeSeleccioado = jtPasajes.getModel().getValueAt(filaSelecionada, 0);
            int idPasaje = (int) idPasajeSeleccioado;
            
            pasaData.eliminarPasaje(idPasaje);
            
            jTdnipasajero.setText("");
            jBEliminar.setEnabled(false);
            
        }
        
        borrarFilas();
                               
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jbBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarDniActionPerformed
       
        if (!jTdnipasajero.getText().isEmpty()) {
            borrarFilas();
        
        int dni = Integer.parseInt(jTdnipasajero.getText());
        
        Pasajero pas = pasData.buscarPasajeroPorDNI(dni);
        
        pasajes = pasaData.buscarPasajesPorPasajero(pas);
        
        cargarPasajes(pasajes);
        
        jBEliminar.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            return;
        }
        
    }//GEN-LAST:event_jbBuscarDniActionPerformed

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID_Ruta");
        filaCabecera.add("Pasajero");
        filaCabecera.add("Colectivo");
        filaCabecera.add("Ruta");
        filaCabecera.add("Fecha Viaje");
        filaCabecera.add("Hora Viaje");
        filaCabecera.add("Precio");
        filaCabecera.add("Asiento");

        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        jtPasajes.setModel(modelo);
        
        TableColumnModel columnModel = jtPasajes.getColumnModel();
        TableColumn column = columnModel.getColumn(0);
        jtPasajes.removeColumn(column);

    }
    
    private void cargarPasajes(List<Pasaje> pasajes) {

        for (Pasaje pas : pasajes) {
            modelo.addRow(new Object[]{pas.getIdPasaje(),pas.getPasajero(),
                pas.getColectivo(),pas.getRuta(),pas.getFechaViaje(),pas.getHoraViaje(),pas.getPrecio(),pas.getAsiento()});
            
        }

    }
    
    private void borrarFilas() {
        int indice = modelo.getRowCount() - 1;

        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTdnipasajero;
    private javax.swing.JButton jbBuscarDni;
    private javax.swing.JTable jtPasajes;
    // End of variables declaration//GEN-END:variables
}
